{% set name = "rrparser" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8fb4ee26fedc78a9e1d9946ad3b9bedc52bcc793e3d62ddab4a79061ff13ae0a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=1.5.3
    - brs_utils
    - colorlog

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - python -m {{ name|lower }} --help
    - python -m pytest -v

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: 'Reaction Rules Parser: retrieves the reaction rules from RetroRules'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
